require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CommitteeMembersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # CommitteeMember. As you add validations to CommitteeMember, be sure to
  # adjust the attributes here as well.

  before(:each) do
    @contract = FactoryGirl.build(:contract)
    @contract.committees = [ FactoryGirl.build(:committee) ]
    @contract.save
    @committee = @contract.committees.first
  end

  let(:valid_attributes) {
    {
      member_name: "Member 1",
      leader: false,
      committee_id: @committee.id
    }
  }

  let(:invalid_attributes) {
    {
      member_name: "",
      leader: nil,
      committee_id: nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommitteeMembersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all committee_members as @committee_members" do
      committee_member = CommitteeMember.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:committee_members)).to eq([committee_member])
    end
  end

  describe "GET #show" do
    it "assigns the requested committee_member as @committee_member" do
      committee_member = CommitteeMember.create! valid_attributes
      get :show, {:id => committee_member.to_param}, valid_session
      expect(assigns(:committee_member)).to eq(committee_member)
    end
  end

  describe "GET #new" do
    it "assigns a new committee_member as @committee_member" do
      get :new, {}, valid_session
      expect(assigns(:committee_member)).to be_a_new(CommitteeMember)
    end
  end

  describe "GET #edit" do
    it "assigns the requested committee_member as @committee_member" do
      committee_member = CommitteeMember.create! valid_attributes
      get :edit, {:id => committee_member.to_param}, valid_session
      expect(assigns(:committee_member)).to eq(committee_member)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new CommitteeMember" do
        expect {
          post :create, {:committee_member => valid_attributes}, valid_session
        }.to change(CommitteeMember, :count).by(1)
      end

      it "assigns a newly created committee_member as @committee_member" do
        post :create, {:committee_member => valid_attributes}, valid_session
        expect(assigns(:committee_member)).to be_a(CommitteeMember)
        expect(assigns(:committee_member)).to be_persisted
      end

      it "redirects to the created committee_member" do
        post :create, {:committee_member => valid_attributes}, valid_session
        expect(response).to redirect_to(CommitteeMember.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved committee_member as @committee_member" do
        post :create, {:committee_member => invalid_attributes}, valid_session
        expect(assigns(:committee_member)).to be_a_new(CommitteeMember)
      end

      it "re-renders the 'new' template" do
        post :create, {:committee_member => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
          member_name: "Member 2",
          leader: false,
          committee_id: @committee.id
        }
      }

      it "updates the requested committee_member" do
        committee_member = CommitteeMember.create! valid_attributes
        put :update, {:id => committee_member.to_param, :committee_member => new_attributes}, valid_session
        committee_member.reload
        expect(assigns(:committee_member).member_name).to match(new_attributes[:member_name])
      end

      it "assigns the requested committee_member as @committee_member" do
        committee_member = CommitteeMember.create! valid_attributes
        put :update, {:id => committee_member.to_param, :committee_member => valid_attributes}, valid_session
        expect(assigns(:committee_member)).to eq(committee_member)
      end

      it "redirects to the committee_member" do
        committee_member = CommitteeMember.create! valid_attributes
        put :update, {:id => committee_member.to_param, :committee_member => valid_attributes}, valid_session
        expect(response).to redirect_to(committee_member)
      end
    end

    context "with invalid params" do
      it "assigns the committee_member as @committee_member" do
        committee_member = CommitteeMember.create! valid_attributes
        put :update, {:id => committee_member.to_param, :committee_member => invalid_attributes}, valid_session
        expect(assigns(:committee_member)).to eq(committee_member)
      end

      it "re-renders the 'edit' template" do
        committee_member = CommitteeMember.create! valid_attributes
        put :update, {:id => committee_member.to_param, :committee_member => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested committee_member" do
      committee_member = CommitteeMember.create! valid_attributes
      expect {
        delete :destroy, {:id => committee_member.to_param}, valid_session
      }.to change(CommitteeMember, :count).by(-1)
    end

    it "redirects to the committee_members list" do
      committee_member = CommitteeMember.create! valid_attributes
      delete :destroy, {:id => committee_member.to_param}, valid_session
      expect(response).to redirect_to(committee_members_url)
    end
  end

end
